@startuml component-view
!include <C4/C4_Component.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>
!include <tupadr3/devicons2/angularjs>


LAYOUT_LEFT_RIGHT()




title Component view for the Online Shop Monolith example
Person(softwareDevelopment_architecture_example_monolith_customer, "Customer", $descr="A customer who buys products from the online shop.")
System_Ext(softwareDevelopment_architecture_example_monolith_paymentSystem, "Payment System", $descr="Handles Credit Card, PayPal, etc.")
System_Ext(softwareDevelopment_architecture_example_monolith_logisticsSystem, "Logistics System", $descr="Handles shipping with DHL, UPS, etc.")
System_Ext(softwareDevelopment_architecture_example_monolith_emailSystem, "Email System", $descr="Sends Emails e.g. to customers")
System_Boundary(softwareDevelopment_architecture_example_monolith_onlineShopSystem, "Online Shop") {
  Container(softwareDevelopment_architecture_example_monolith_onlineShopBackend, "Online Shop Backend Application", $techn="Java EE")
  ContainerDb(softwareDevelopment_architecture_example_monolith_onlineShopDb, "Online Shop Database", $techn="DB/2")
  Container(softwareDevelopment_architecture_example_monolith_onlineShopFrontend, "Online Shop Frontend Application", $techn="AngularJS", $sprite="angularjs")
}
Rel(softwareDevelopment_architecture_example_monolith_onlineShopBackend, softwareDevelopment_architecture_example_monolith_emailSystem, "sends email", $descr="order confirmation, shipping notification")
Rel(softwareDevelopment_architecture_example_monolith_onlineShopFrontend, softwareDevelopment_architecture_example_monolith_onlineShopBackend, "calls", $descr="get products, place orders.", $techn="HTTPS")
Rel(softwareDevelopment_architecture_example_monolith_customer, softwareDevelopment_architecture_example_monolith_onlineShopFrontend, "uses", $descr="browse products, place orders", $techn="HTTPS")
Rel_L(softwareDevelopment_architecture_example_monolith_onlineShopBackend, softwareDevelopment_architecture_example_monolith_onlineShopDb, "store and query", $descr="products, orders", $techn="JDBC")
Rel(softwareDevelopment_architecture_example_monolith_onlineShopBackend, softwareDevelopment_architecture_example_monolith_paymentSystem, "process payment", $descr="credit card, paypal", $techn="REST")
Rel(softwareDevelopment_architecture_example_monolith_onlineShopBackend, softwareDevelopment_architecture_example_monolith_logisticsSystem, "ship", $descr="order", $techn="REST")
SHOW_LEGEND()
@enduml
