@startuml container-view
!include <C4/C4_Container.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>
!include <tupadr3/devicons2/angularjs>


LAYOUT_LEFT_RIGHT()




title Container view for the Online Shop modulith example
System_Ext(softwareDevelopment_architecture_example_modulith_emailSystem, "Email System", $descr="Sends Emails e.g. to customers")
System_Boundary(softwareDevelopment_architecture_example_modulith_onlineShopSystem, "Online Shop") {
  Container(softwareDevelopment_architecture_example_modulith_onlineShopFrontend, "Online Shop Frontend Application", $techn="AngularJS", $sprite="angularjs")
  Container(softwareDevelopment_architecture_example_modulith_onlineShopBackend, "Online Shop Backend Application", $techn="Java EE")
  ContainerDb(softwareDevelopment_architecture_example_modulith_onlineShopDb, "Online Shop Database", $descr="Stores products, orders, payments, etc.", $techn="DB/2")
}
Person(softwareDevelopment_architecture_example_modulith_customer, "Customer", $descr="A customer who buys products from the online shop.")
System_Ext(softwareDevelopment_architecture_example_modulith_logisticsSystem, "Logistics System", $descr="Handles shipping with DHL, UPS, etc.")
System_Ext(softwareDevelopment_architecture_example_modulith_paymentSystem, "Payment System", $descr="Handles Credit Card, PayPal, etc.")
Rel(softwareDevelopment_architecture_example_modulith_onlineShopBackend, softwareDevelopment_architecture_example_modulith_logisticsSystem, "ship", $descr="order", $techn="REST")
Rel(softwareDevelopment_architecture_example_modulith_onlineShopBackend, softwareDevelopment_architecture_example_modulith_paymentSystem, "process payment", $descr="credit card, paypal", $techn="REST")
Rel(softwareDevelopment_architecture_example_modulith_customer, softwareDevelopment_architecture_example_modulith_onlineShopFrontend, "uses", $descr="browse products, place orders", $techn="HTTPS")
Rel(softwareDevelopment_architecture_example_modulith_onlineShopBackend, softwareDevelopment_architecture_example_modulith_emailSystem, "sends email", $descr="order confirmation, shipping notification")
Rel(softwareDevelopment_architecture_example_modulith_onlineShopFrontend, softwareDevelopment_architecture_example_modulith_onlineShopBackend, "calls", $descr="get products, place orders.", $techn="HTTPS")
Rel_L(softwareDevelopment_architecture_example_modulith_onlineShopBackend, softwareDevelopment_architecture_example_modulith_onlineShopDb, "store and query", $descr="products, orders", $techn="JDBC")
SHOW_LEGEND()
@enduml
