@startuml deployment-view
!include <C4/C4_Deployment.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>







title Deployment view for the Online Shop modulith example
Node(softwareDevelopment_architecture_example_modulith_dataCenter, "Data Center", $descr="The data center where the online shop is hosted.") {
  Node(softwareDevelopment_architecture_example_modulith_internalNetwork, "Internal Network") {
    Node(softwareDevelopment_architecture_example_modulith_appVm1, "App VM 1", $descr="Application Server Virtual Machine 1", $type="VMware vSphere") {
      Node(softwareDevelopment_architecture_example_modulith_applicationServer, "Application Server", $type="IBM WebSphere") {
        Container(softwareDevelopment_architecture_example_modulith_onlineShopBackend, "Online Shop Backend Application", $techn="Java EE")
      }
    }
    Node(softwareDevelopment_architecture_example_modulith_dbVm1, "DB VM 1", $descr="Database Server Virtual Machine 1", $type="VMware vSphere") {
      Node(softwareDevelopment_architecture_example_modulith_dbServer, "Database Server", $type="DB/2") {
        ContainerDb(softwareDevelopment_architecture_example_modulith_onlineShopDb, "Online Shop Database", $descr="Stores products, orders, payments, etc.", $techn="DB/2")
      }
    }
  }
  Node(softwareDevelopment_architecture_example_modulith_perimeterNetwork, "Perimeter Network") {
    Node(softwareDevelopment_architecture_example_modulith_webVm1, "Web VM 1", $descr="Web Server Virtual Machine 1", $type="VMware vSphere") {
      Node(softwareDevelopment_architecture_example_modulith_webServer, "Web Server", $type="Apache Tomcat") {
        Container(softwareDevelopment_architecture_example_modulith_onlineShopFrontend, "Online Shop Frontend Application", $techn="AngularJS", $sprite="angularjs")
      }
    }
  }
}
Rel(softwareDevelopment_architecture_example_modulith_perimeterNetwork, softwareDevelopment_architecture_example_modulith_internalNetwork, "links to", $descr="The Perimeter Network links to the Internal Network via firewall.")
SHOW_LEGEND()
@enduml
