@startuml simple-restful-container-view
!include <C4/C4_Container.puml>
!include <awslib14/AWSCommon>
!include <awslib14/AWSC4Integration>
!include <azure/AzureCommon>
!include <azure/AzureC4Integration>
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/java>
!include <tupadr3/font-awesome-5/react>
!include <tupadr3/devicons2/typescript>
!include <tupadr3/devicons2/go>
!include <tupadr3/devicons2/kotlin>


LAYOUT_LEFT_RIGHT()




title Container View for the simple RESTful Communication Microservices Example
Container(softwareDevelopment_architecture_example_microservices_inventoryService, "Inventory Service", $descr="Handles inventory", $techn="Java, Spring Boot", $sprite="java")
Container(softwareDevelopment_architecture_example_microservices_shopFrontend, "Shop Frontend", $descr="The frontend of the online shop", $techn="React, Typescript", $sprite="react")
Container(softwareDevelopment_architecture_example_microservices_shippingService, "Shipping Service", $descr="Handles shipping", $techn="Go", $sprite="go")
Container(softwareDevelopment_architecture_example_microservices_orderService, "Order Service", $descr="Handles orders", $techn="Java, Spring Boot", $sprite="java")
Container(softwareDevelopment_architecture_example_microservices_notificationService, "Notification Service", $descr="Handles notifications")
Container(softwareDevelopment_architecture_example_microservices_paymentService, "Payment Service", $descr="Handles payments", $techn="Kotlin, Quarkus", $sprite="kotlin")
Person(softwareDevelopment_architecture_example_microservices_customer, "Customer", $descr="A customer of the online shop")
Rel(softwareDevelopment_architecture_example_microservices_shopFrontend, softwareDevelopment_architecture_example_microservices_orderService, "calls", $descr="get products, place orders")
Rel(softwareDevelopment_architecture_example_microservices_orderService, softwareDevelopment_architecture_example_microservices_shippingService, "request", $descr="Ship Order", $techn="REST")
Rel(softwareDevelopment_architecture_example_microservices_orderService, softwareDevelopment_architecture_example_microservices_notificationService, "request", $descr="Notify Customer", $techn="REST")
Rel(softwareDevelopment_architecture_example_microservices_customer, softwareDevelopment_architecture_example_microservices_shopFrontend, "uses", $descr="browse products, place orders")
Rel(softwareDevelopment_architecture_example_microservices_orderService, softwareDevelopment_architecture_example_microservices_inventoryService, "request", $descr="Update Inventory", $techn="REST")
Rel(softwareDevelopment_architecture_example_microservices_orderService, softwareDevelopment_architecture_example_microservices_paymentService, "request", $descr="Payment for Order", $techn="REST")
SHOW_LEGEND()
@enduml
