@startuml code-view



skinparam linetype ortho


title Code View of the Clean Architecture Blueprint

package "adapter" as softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter {
  package "rest" as softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_rest {
    class "RestController" as softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_rest_restController {}
  }
  package "repository" as softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_repository {
    class "SqlRepository" as softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_repository_sqlRepository {}
    class "InMemoryRepository" as softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_repository_inMemoryRepository {}
  }
  package "event-publisher" as softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_eventPublisher {
    class "KafkaEventPublisher" as softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_eventPublisher_kafkaEventPublisher {}
  }
}
package "domain" as softwareDevelopment_architecture_blueprint_cleanArchitecture_domain {
  class "DomainAggregate" as softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainAggregate {}
  class "DomainValue" as softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainValue {}
  class "DomainService" as softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainService {}
  class "DomainEntity" as softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainEntity {}
  abstract class "DomainEvent" as softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainEvent {}
}
package "application" as softwareDevelopment_architecture_blueprint_cleanArchitecture_application {
  interface "RepositoryInterface" as softwareDevelopment_architecture_blueprint_cleanArchitecture_application_repositoryInterface {}
  interface "DomainEventPublisherInterface" as softwareDevelopment_architecture_blueprint_cleanArchitecture_application_domainEventPublisherInterface {
    publish()
  }
  class "ApplicationService" as softwareDevelopment_architecture_blueprint_cleanArchitecture_application_applicationService {}
}
softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainAggregate *--> softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainValue
softwareDevelopment_architecture_blueprint_cleanArchitecture_application_repositoryInterface <|.up. softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_repository_sqlRepository
softwareDevelopment_architecture_blueprint_cleanArchitecture_application_domainEventPublisherInterface <|.. softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_eventPublisher_kafkaEventPublisher
softwareDevelopment_architecture_blueprint_cleanArchitecture_application_repositoryInterface <|.up. softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_repository_inMemoryRepository
softwareDevelopment_architecture_blueprint_cleanArchitecture_application_applicationService ..> softwareDevelopment_architecture_blueprint_cleanArchitecture_application_domainEventPublisherInterface
softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainAggregate *--> softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainEntity
softwareDevelopment_architecture_blueprint_cleanArchitecture_application_applicationService ..> softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainService
softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter .down.> softwareDevelopment_architecture_blueprint_cleanArchitecture_application
softwareDevelopment_architecture_blueprint_cleanArchitecture_adapter_rest_restController ..> softwareDevelopment_architecture_blueprint_cleanArchitecture_application_applicationService
softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainService ..> softwareDevelopment_architecture_blueprint_cleanArchitecture_domain_domainAggregate
softwareDevelopment_architecture_blueprint_cleanArchitecture_application ..> softwareDevelopment_architecture_blueprint_cleanArchitecture_domain
softwareDevelopment_architecture_blueprint_cleanArchitecture_application_applicationService ..> softwareDevelopment_architecture_blueprint_cleanArchitecture_application_repositoryInterface
@enduml
